# Schema for the configuration of the Section Library module.

section_library.settings:
  type: config_object
  label: 'Section library settings'
  constraints:
    FullyValidatable: ~
  mapping:
    section_label:
      type: required_label
      label: 'Section label'
    template_label:
      type: required_label
      label: 'Template label'
